config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('gestiontorii/', admin.site.urls),
    path('',include('torii.home.urls')),
    path('',include('torii.institute.urls')),
    path('',include('torii.contact.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torii/contact/urls.py
from django.urls import path
from torii.contact.views import contact_form


app_name = 'contact'

urlpatterns = [
    path('contact/', contact_form,name="contact-form"),
]

torii/home/urls.py
from django.contrib import admin
from django.urls import path
from torii.home.views import home, about


app_name = 'home'

urlpatterns = [
    path('', home,name="homepage"),
    path('about/', about,name="about"),


]

torii/institute/urls.py
from django.contrib import admin
from django.urls import path
from torii.institute.views import japanese_courses,chinese_courses, korean_courses, other_courses, workshops


app_name = 'institute'

urlpatterns = [
    path('japonais/', japanese_courses,name="japanese"),
    path('chinois/', chinese_courses,name="chinese"),
    path('coreen/', korean_courses,name="korean"),
    path('ateliers/', workshops,name="workshops"),
    path('autre/', other_courses,name="other"),

]

torii/contact/models.py
from django.db import models
from django.core.validators import RegexValidator

phone_regex = RegexValidator(
    regex=r'^(?:(?:\+213|0)(?:5|6|7)\d{8}|\+\d{1,3}\d{4,14})$',
    message="Le numéro de téléphone doit être au format algérien '0555324574' ou '+213555696868', ou international '+<indicatif><numéro>' (minimum 4 chiffres après l'indicatif, maximum 14 chiffres).")

class Contact(models.Model):
    JAPANESE_IN_PERSON = 'Cours de japonais en présentiel'
    JAPANESE_ONLINE = 'Cours de japonais en ligne'
    JAPANESE_INDIVIDUAL = 'Cours de japonais individuel'
    CHINESE_IN_PERSON = 'Cours de chinois en présentiel'
    CHINESE_ONLINE = 'Cours de chinois en ligne'
    CHINESE_INDIVIDUAL = 'Cours de chinois individuel'
    KOREAN_IN_PERSON = 'Cours de coréen en présentiel'
    KOREAN_ONLINE = 'Cours de coréen en ligne'
    KOREAN_INDIVIDUAL = 'Cours de coréen individuel'
    WORKSHOP = 'Atelier'
    OTHER = 'Autre'

    REASON_CHOICES = [
        (JAPANESE_IN_PERSON, 'Cours de japonais en présentiel'),
        (JAPANESE_ONLINE, 'Cours de japonais en ligne'),
        (JAPANESE_INDIVIDUAL, 'Cours de japonais individuel'),
        (CHINESE_IN_PERSON, 'Cours de chinois en présentiel'),
        (CHINESE_ONLINE, 'Cours de chinois en ligne'),
        (CHINESE_INDIVIDUAL, 'Cours de chinois individuel'),
        (KOREAN_IN_PERSON, 'Cours de coréen en présentiel'),
        (KOREAN_ONLINE, 'Cours de coréen en ligne'),
        (KOREAN_INDIVIDUAL, 'Cours de coréen individuel'),
        (WORKSHOP, 'Atelier'),
        (OTHER, 'Autre'),
    ]

    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, validators=[phone_regex])
    reason_for_contact = models.CharField(max_length=50, choices=REASON_CHOICES)
    why_contact_us = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} | {self.reason_for_contact} |{self.created_at}'
    

torii/home/models.py
from django.db import models

# Create your models here.

torii/institute/models.py
from django.db import models


class Subject(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    type = models.ForeignKey(to="SubjectType",on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    thumbnail = models.ImageField(upload_to="img", blank=True, null=True)
    english_title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Gallery(models.Model):
    title = models.CharField(max_length=100,blank=True)
    thumbnail = models.ImageField(upload_to="img", blank=True, null=True)

    def __str__(self) -> str:
        return self.title



class Course(models.Model):
    ENROLLMENT_STATUS_CHOICES = [
        ('En cours', 'En cours'),
        ('Terminée', 'Terminée'),
    ]

    COURSE_TYPE_CHOICES = [
        ('individual', 'Individuel'),
        ('online', 'En ligne'),
        ('presential', 'Présentiel en groupe'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    frequency = models.CharField(max_length=100, blank=True, null=True)
    days = models.CharField(max_length=200, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    hour = models.CharField(max_length=255,blank=True, null=True)
    duration=models.CharField(max_length=150,blank=True)
    type = models.CharField(max_length=20, choices=COURSE_TYPE_CHOICES)
    price = models.IntegerField()
    subject = models.ForeignKey(to='Subject', on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    thumbnail = models.URLField(max_length=200, blank=True, null=True)
    enrollment = models.CharField(
        max_length=10,
        choices=ENROLLMENT_STATUS_CHOICES,
        default='En cours',
    )
    url_file = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f'{self.title} | {self.subject.title}'
    


class SubjectType(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title

    

torii/contact/forms.py
from django import forms
from torii.contact.models import Contact
from django_recaptcha.fields import ReCaptchaField

class ContactForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone_number', 'reason_for_contact', 'why_contact_us']
        labels = {
            'name': 'Nom',
            'email': 'E-mail',
            'phone_number': 'Numéro de téléphone',
            'reason_for_contact': 'Motif de contact',
            'why_contact_us': 'Donnez-nous plus de détails',
        }

torii/contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from torii.contact.models import Contact
from torii.contact.forms import ContactForm

def contact_form(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            
            # Préparer le message HTML pour l'email de notification
            html_message = render_to_string('contact/contact_email.html', {
                'name': contact.name,
                'email': contact.email,
                'phone_number': contact.phone_number,
                'why_contact_us': contact.why_contact_us,
                'reason_for_contact': contact.reason_for_contact,
            })
            
            # Convertir le message HTML en texte brut
            plain_message = strip_tags(html_message)
            
            # Envoyer un email de notification
            send_mail(
                subject='Nouveau message de contact',
                message=plain_message,
                from_email='institut-torii@institut-torii.com',  
                recipient_list=['smm.torii@gmail.com','charger.com.igg@gmail.com'],
                fail_silently=False,
                html_message=html_message,
            )
            
            # Préparer le message HTML pour l'email de confirmation
            confirmation_html_message = render_to_string('contact/confirmation_email.html', {
                'name': contact.name,
            })
            
            # Convertir le message HTML en texte brut
            confirmation_plain_message = strip_tags(confirmation_html_message)
            
            # Envoyer un email de confirmation
            send_mail(
                subject='Nous avons bien reçu ta demande',
                message=confirmation_plain_message,
                from_email='institut-torii@institut-torii.com',
                recipient_list=[contact.email],
                fail_silently=False,
                html_message=confirmation_html_message,
            )
            
            # Rediriger
            return redirect("home:homepage")
    else:
        form = ContactForm()
    return render(request, "contact/contact_form.html", context={"form": form})

torii/home/views.py
from django.shortcuts import render
from torii.institute.models import Subject, Gallery


def home(request):
    subjects = Subject.objects.filter(available=True)
    photos = Gallery.objects.all()
    return render(request, 'home/index.html', {'subjects': subjects, 'photos': photos})


def about(request):
    return render(request, 'home/about.html')

torii/institute/views.py
from django.shortcuts import render
from torii.institute.models import Subject, Course


def japanese_courses(request):
    subject_title = "Japonais"
    courses = Course.objects.filter(subject__title="Japonais")

    return render(request,'institute/japanese.html', context={"courses": courses, "subject_title": subject_title})




def chinese_courses(request):
    subject_title = "Chinois"
    courses = Course.objects.filter(subject__title="Chinois")

    return render(request, 'institute/chinese.html', context={"courses": courses, "subject_title": subject_title})


def korean_courses(request):
    subject_title = "Coréen"
    courses = Course.objects.filter(subject__title="Coréen")

    return render(request, 'institute/korean.html', context={"courses": courses, "subject_title": subject_title})




def other_courses(request):
    subject_title = "Autres"
    courses = Course.objects.filter(subject__title="Autres")

    return render(request, 'institute/other.html', context={"courses": courses, "subject_title": subject_title})



def workshops(request):
    subject_title = "Ateliers"
    courses = Course.objects.filter(subject__title="Ateliers")

    return render(request, 'institute/workshop.html', context={"courses": courses, "subject_title": subject_title})

torii/templates/fragments/footer.html
<footer class="footer footer-center bg-gray-200 text-base-content rounded p-6 w-full text-black">
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover" href="https://maps.app.goo.gl/NRyzbD337Rrkokh5A" target="_blank">
        <i class="fas fa-map-marker-alt"></i>
        <span class="ml-2">Rte de Sebala, El Achour 16000</span>
    </a>
    <a class="link link-hover" href="tel:0540900254">
        <i class="fas fa-phone"></i>
        <span class="ml-2">0557745920</span>
    </a>
    <a class="link link-hover" href="mailto:institut.torii@gmail.com">
        <i class="fas fa-envelope"></i>
        <span class="ml-2">Contact</span>
    </a>
</nav>
        <nav>
          <div class="grid grid-flow-col gap-4">
            <a href="https://www.instagram.com/institut_torii/" target="_blank">
                <i class="fab fa-instagram fa-2x"></i>
            </a>
            <a href="https://www.youtube.com/@instituttorii2543" target="_blank">
                <i class="fab fa-youtube fa-2x"></i>
            </a>
            <a href="https://www.facebook.com/instituttorii/" target="_blank">
                <i class="fab fa-facebook fa-2x"></i>
            </a>
            <a href="https://www.tiktok.com/@institut_torii" target="_blank">
                <i class="fab fa-tiktok fa-2x"></i>
            </a>
        </div>
    </nav>
    <aside>
      <p>Copyright © {% now "Y" %} - All rights reserved by Institut Torii</p>
    </aside>
</footer>

torii/templates/fragments/navigation.html
{% load static %}

<div class="navbar bg-gray-100 sticky top-0 z-50">
    <div class="navbar-start">
        <div class="dropdown">
            <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
                </svg>
            </div>
            <ul tabindex="0" class="menu menu-sm dropdown-content bg-gray-100 rounded-box z-[1] mt-3 w-52 p-2 shadow text-lg">
                <li><a class="text-black" href="{% url 'home:homepage' %}">Accueil</a></li>
                <li>
                    <a class="text-black" >Nos services</a>
                    <ul class="p-2">
                        <li><a class="text-black" href="{% url 'institute:japanese' %}">Cours de japonais</a></li>
                        <li><a class="text-black" href="{% url "institute:chinese" %}">Cours de chinois</a></li>
                        <li><a class="text-black" href="{% url "institute:korean" %}">Cours de coréen</a></li>
                        <li><a class="text-black" href="{% url "institute:workshops"%}" >Ateliers</a></li>
                        <li><a class="text-black" href="{% url "institute:other" %}">Autres</a></li>
                    </ul>
                </li>
                <li><a class="text-black" href="{% url "contact:contact-form" %}">Contact</a></li>
                <li><a class="text-black" href="{% url "home:about" %}">À propos</a></li>
            </ul>
        </div>
        <a class="btn btn-ghost text-xl" href="{% url 'home:homepage' %}">
            <img src="https://instituttorii.sirv.com/Images/logo_horizontal.png" alt="Institut Torii Logo" class="h-14 w-auto">
        </a>
    </div>
    <div class="navbar-center hidden lg:flex">
        <ul class="menu menu-horizontal px-1 text-lg">
            <li class="text-black"><a href="{% url 'home:homepage' %}">Accueil</a></li>
            <li class="text-black relative" id="services-menu">
                <details>
                    <summary>Nos services</summary>
                    <ul class="bg-gray-100 text-black p-2">
                        <li class="text-black"><a href="{% url 'institute:japanese' %}">Cours de japonais</a></li>
                        <li class="text-black"><a href="{% url "institute:chinese" %}">Cours de chinois</a></li>
                        <li class="text-black"><a href="{% url "institute:korean" %}">Cours de coréen</a></li>
                        <li class="text-black"><a href="{% url "institute:workshops" %}">Ateliers</a></li>
                        <li class="text-black"><a href="{% url "institute:other" %}">Autres</a></li>
                    </ul>
                </details>
            </li>
            <li class="text-black"><a href="{% url "contact:contact-form" %}">Contact</a></li>
            <li class="text-black"><a href="{% url "home:about" %}">À propos</a></li>
        </ul>
    </div>
    <div class="navbar-end">
        <a href="tel:0557745920" class="btn bg-red-400 text-white hover:bg-red-500 focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-opacity-50">
            <i class="fa fa-phone" aria-hidden="true"></i>
        </a>
    </div>
</div>

<script>
    document.addEventListener('click', function(event) {
        var servicesMenu = document.getElementById('services-menu');
        var isClickInside = servicesMenu.contains(event.target);

        if (!isClickInside) {
            var detailsElement = servicesMenu.querySelector('details');
            detailsElement.removeAttribute('open');
        }
    });
</script>

torii/templates/fragments/no_courses.html
<div class="text-center py-8">
    <h2 class="text-2xl font-bold text-gray-700">Aucun cours disponible pour le moment</h2>
    <p class="text-gray-500 mt-4">Veuillez revenir plus tard pour voir les nouveaux cours disponibles.</p>
</div>

torii/templates/fragments/wrapper.html
{% load static %}

<!-- wrapper.html -->